# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbf939564f67444b8a17eff63bbbf244304c7c5f187f127b174a45a3448157d0a2ed2441c967da8a7938b294fc6a4a1bcec58d34c04876070c9104a74e304bba

test:
  secret_key_base: 0252d9cf560f5dadfeba4ccb13f47a417ebb6215bec09945358544fcd0a28c61dde7e30a85efd63fdd6dd94bea09d862fd18e97f6c7861c9207f332c693e2904

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
